Update-webhooks-types
Genez-io/genezio-documentation pull request #70
Opened 2024-03-29 14:23 UTC by Virgil993

2024-04-05 12:37 UTC, costinsin requested changes

2024-04-05 12:37 UTC, costinsin commented on docs/features/http-methods-webhooks.md
You forgot to remove the imports from `@genezio/types`.

2024-04-05 12:37 UTC, costinsin commented on docs/features/http-methods-webhooks.md
> +      For TypeScript projects the expected type for the request and response objects are the standard `Request` and `Response` objects provided by the @types/node library. To use these types in your
```suggestion
      For TypeScript projects the expected type for the request and response objects are the standard `Request` and `Response` objects provided by the `@types/node` library. To use these types in your project, you need to install the `@types/node` package by running the following command:
```

2024-04-05 12:37 UTC, costinsin commented on docs/features/http-methods-webhooks.md
> +</Tabs>
Isn't this section duplicated with the `info` Admonition above? I would remove it entirely.

2024-08-29 12:25 UTC, closed without merging

2024-08-29 12:25 UTC, andreia-oca commented
This is not active anymore